nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-berry.cjs

npmScopes:
  "nexthcm":
    npmAlwaysAuth: true
    npmRegistryServer: https://maven.banvien.com.vn/repository/npm-hosted
    npmAuthToken: NpmToken.5bb14fb0-8f1d-3cd8-9d1b-679598063448
