const { getJestProjects } = require('@nrwl/jest');

module.exports = {
  projects: [
    ...getJestProjects(),
    '<rootDir>/apps/hcm-web',
    '<rootDir>/libs/core',
    '<rootDir>/libs/auth',
    '<rootDir>/libs/my-time',
    '<rootDir>/libs/payslip',
    '<rootDir>/libs/report',
    '<rootDir>/libs/human-resource',
    '<rootDir>/libs/form',
    '<rootDir>/libs/knowledge-base',
    '<rootDir>/libs/notifications',
    '<rootDir>/libs/configurations',
    '<rootDir>/libs/ui',
    '<rootDir>/libs/home',
    '<rootDir>/libs/workflow-designer',
    '<rootDir>/apps/hcm-workflows',
    '<rootDir>/libs/admin/workflows',
    '<rootDir>/libs/admin/tenants',
    '<rootDir>/libs/admin/offices',
    '<rootDir>/libs/admin/permissions',
    '<rootDir>/libs/admin/job-level',
    '<rootDir>/libs/admin/team-building-allowance',
    '<rootDir>/libs/admin/knowledge-base',
    '<rootDir>/libs/admin/entitlement',
    '<rootDir>/libs/admin/job-titles',
    '<rootDir>/libs/chat',
    '<rootDir>/libs/admin/leave-configs',
    '<rootDir>/libs/admin/employees',
    '<rootDir>/libs/admin/user-roles',
    '<rootDir>/libs/admin/working-times',
    '<rootDir>/libs/admin/seat-maps',
  ],
};
