GET https://qa-nexthcm-api.banvien.com.vn/accountapp/v1.0/employees
Authorization: Bearer {{auth_token}}

###
GET https://qa-nexthcm-api.banvien.com.vn/mytimeapp/v1.0/leave-entitlement-transfer/remaining-entitlement-to-cast
Authorization: Bearer {{auth_token}}
