export enum NotificationType {
  OverviewMe = 2,
  Permission,
  SeatMap,
  KnowledgeBaseArticles,
  EmployeeLeave,
  EmployeeWorkingAfterHouse,
  EmployeeUpdateTimesheet,
  EmployeeWorkingOnsite,
  EmployeeWorkFromHome,
  AdminWorkingAfterHouse,
  AdminUpdateTimesheet,
  AdminWorkingOnsite,
  AdminWorkFromHome,
  AdminLeave,
  ProfileIndividual,
  Tenants,
  OfficesList,
  SeatMapEdit,
  LeaveConfigType = 21,
  LeaveConfigEntitlements,
  LeaveConfigLevelsApproval = 24,
  WorkingTimesConfiguration = 26,
}
