https://qa-nexthcm-api.banvien.com.vn/accountapp/v1.0/networks
Authorization: Bearer {{auth_token}}

###
POST https://qa-nexthcm-api.banvien.com.vn/accountapp/v1.0/networks
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "wifiSSID": "1234567",
    "macAddress": "00-01-02-03-04",
    "description": "BanVien",
    "office": {
        "id": "819d6a9d-b60a-4b6f-bafb-49079843170b",
        "office_name": "Copac",
        "address": "Quận 4"
    }
}
