POST https://dev-nexthcm-api.banvien.com.vn/accountapp/v1.0/auth
Content-Type: application/json

{
  "username": "ban.vien.solutions.admin",
  "password": "123456",
  "rememberMe": false
}

> {% client.global.set("auth_token", response.body.access_token); %}
